services:
  traefik:
    build:
      context: ./traefik
    ports:
      - 5003:5003
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
  web:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev